# pyocd pipelines

trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
- job: functional_test
  displayName: "Functional tests"
  pool: default
  timeoutInMinutes: 200
  steps:
  # Activate venv and install dependencies.
  - script: |
      python3 -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip setuptools wheel
      pip install -r dev-requirements.txt
    displayName: 'Install dependencies'

  - script: |
      cd test
      python ./automated_test.py
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: test/output/*.xml
    displayName: "Publish results"

